[en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-CA'
    languageDirection = 'ltr'
    languageName = 'English'
    [en.pagination]
        disableAliases = false
        pagerSize = 6
        path = 'page'

[cn]
    title = '龙雪娇的主页'
    contentDir = 'content/cn'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    [cn.pagination]
        disableAliases = false
        pagerSize = 6
        path = '主页'
        languageName = 'Mandarin'
    ##[id.pagination]
      ##  disableAliases = false
        ##pagerSize = 12
        ##path = 'laman'
    ##[id.params]
       ## copyright = 'janetlongxj <i class="icon copyleft"></i> 2025'

    ##[id.params.feed]
      ##  flowlines = false
    # [id.params.home]
    #     disableListing = true
    ##[id.sitemap]
      ##  changeFreq = 'always' ## Change posts listings layout

